#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    command: python /code/CINS465Project/manage.py runserver 0.0.0.0:8000
    #command: python /code/CINS465Project/manage.py runserver cins465project.ddns.net:8000

  nginx:
     restart: always
     build: ./nginx/
     depends_on:
       - web
     ports:
       - 80:80
     links:
       - web:web