# Generated by Django 4.0.4 on 2022-05-07 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
