# Generated by Django 4.0.4 on 2022-05-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_user_comment_profile_rename_user_post_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='user',
        ),
    ]
